DB_FILE         = 'brblog.db'
DEBUG           = True
# openssl rand -base64 32
SECRET_KEY      = 
# as generated by make_pw_digest()
PASSWORD_DIGEST = 

BLOG_TITLE      = 
POSTS_PER_PAGE  = 16
TIME_ADJ        = 'localtime'
SEP             = 'or'
